[package]
name = "yahoo-finance-info"
version = "0.1.0"
edition = "2021"

[dependencies]
yahoo_finance_api = {version = "2.4.0"}

[dev-dependencies]
tokio-test = "0.4.4"
tokio = { version = "1.42.0", features = ["macros"] }