[package]
name = "ETF-investment-plan"
version = "0.1.0"
edition = "2021"

[dependencies]
yahoo-finance-info = { path = "yahoo-finance-info"}
investment-planner = { path = "investment-planner" }
derive-new = "0.7.0"
tokio = {version = "1.42.0", features = ["rt", "macros"]}
futures = "0.3.31"